import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// https://flowbite.com/blocks/e-commerce/product-cards/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // {inter.className}
    <html>
      <body
        className="bg-gray-100 dark:bg-zinc-900 transition-all
      duration-700"
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
